export const CDR_COLUMNS = [
  "Servicos",
  "DataRow",
  "CallID",
  "MSISDN",
  "ANI",
  "DNIS",
  "CodigoAplicacao",
  "VersaoAplicacao",
  "DataInicioLigacaoUra",
  "DataFimLigacaoUra",
  "DisconnectionTypeDesc",
  "DuracaoTotalChamada",
  "DuracaoChamadaUra",
  "AccessCodeEntrada",
  "DigitCode",
  "MPLGrupo",
  "GrupoFuncional",
  "ScriptPointDesc",
  "IdSkill",
  "Cti",
  "NomeSkill",
  "Transfercode",
  "DNA",
  "Segmento",
  "CogDhInicioSegmento",
  "CogTempoSegmento",
  "CogJornada",
  "CogEntrou",
  "CogInteragiu",
  "CogQtdInteracoes",
  "CogEntendido",
  "CogTextoFalaCliente",
  "InfoAdicional",
  "CogTempoStt",
  "CogTempoIa",
  "CogScriptPointIa",
  "CogTempoFalaCliente",
  "CogTempoTopo",
];

export const FIELD_OPTIONS = [
  { value: "0", label: "Nenhum" },
  { value: "call_id", label: "CALLID" },
  { value: "msisdn", label: "MSISDN" },
  { value: "ani", label: "ANI" },
  { value: "dnis", label: "DNIS" },
  { value: "codigo_aplicacao", label: "CODIGO APLICACAO" },
  { value: "versao_aplicacao", label: "VERSAO APLICACAO" },
  { value: "data_inicio_ligacao_ura", label: "DATA INICIO LIGACAO URA" },
  { value: "data_fim_ligacao_ura", label: "DATA FIM LIGACAO URA" },
  { value: "disconnection_type_desc", label: "DISCONNECTION TYPE DESC" },
  { value: "duracao_total_chamada", label: "DURACAO TOTAL CHAMADA" },
  { value: "duracao_chamada_ura", label: "DURACAO CHAMADA URA" },
  { value: "access_code_entrada", label: "ACCESS CODE ENTRADA" },
  { value: "digit_code", label: "DIGIT CODE" },
  { value: "mpl_grupo", label: "MPL GRUPO" },
  { value: "grupo_funcional", label: "GRUPO FUNCIONAL" },
  { value: "script_point_desc", label: "SCRIPT POINT DESC" },
  { value: "id_skill", label: "ID SKILL" },
  { value: "cti", label: "CTI" },
  { value: "nome_skill", label: "NOME SKILL" },
  { value: "transfercode", label: "TRANSFERCODE" },
  { value: "dna", label: "DNA" },
  { value: "segmento", label: "SEGMENTO" },
  { value: "cog_dh_inicio_segmento", label: "COG DH INICIO SEGMENTO" },
  { value: "cog_tempo_segmento", label: "COG TEMPO SEGMENTO" },
  { value: "cog_jornada", label: "COG JORNADA" },
  { value: "cog_entrou", label: "COG ENTROU" },
  { value: "cog_interagiu", label: "COG INTERAGIU" },
  { value: "cog_qtd_interacoes", label: "COG QTD INTERACOES" },
  { value: "cog_entendido", label: "COG ENTENDIDO" },
  { value: "cog_texto_fala_cliente", label: "COG TEXTO FALA CLIENTE" },
  { value: "info_adicional", label: "INFO ADICIONAL" },
  { value: "cog_tempo_stt", label: "COG TEMPO STT" },
  { value: "cog_tempo_ia", label: "COG TEMPO IA" },
  { value: "cog_script_point_ia", label: "COG SCRIPTPOINT IA" },
  { value: "cog_tempo_fala_cliente", label: "COG TEMPO FALA CLIENTE" },
  { value: "cog_tempo_topo", label: "COG TEMPO TOPO" },
];
