export const CDR_COLUMNS = [
  "Servicos",
  "DataRow",
  "CallID",
  "MSISDN",
  "ANI",
  "DNIS",
  "CodigoAplicacao",
  "VersaoAplicacao",
  "DataInicioLigacaoUra",
  "DataFimLigacaoUra",
  "DisconnectionTypeDesc",
  "DuracaoTotalChamada",
  "DuracaoChamadaUra",
  "AccessCodeEntrada",
  "DigitCode",
  "MPLGrupo",
  "GrupoFuncional",
  "ScriptPointDesc",
  "IdSkill",
  "Cti",
  "NomeSkill",
  "Transfercode",
  "DNA",
  "Segmento",
  "CogDhInicioSegmento",
  "CogTempoSegmento",
  "CogJornada",
  "CogEntrou",
  "CogInteragiu",
  "CogQtdInteracoes",
  "CogEntendido",
  "CogTextoFalaCliente",
  "InfoAdicional",
  "CogTempoStt",
  "CogTempoIa",
  "CogScriptPointIa",
  "CogTempoFalaCliente",
  "CogTempoTopo",
];

export const FIELD_OPTIONS = [
  { value: "0", label: "Nenhum" },
  { value: "ani", label: "ANI" },
  { value: "msisdn", label: "MSISDN" },
  { value: "dnis", label: "DNIS" },
  { value: "callId", label: "CallID" },
  { value: "codigoAplicacao", label: "Codigo Aplicacao" },
  { value: "versaoAplicacao", label: "Versao Aplicacao" },
  { value: "disconnectionTypeDesc", label: "Disconnection Type" },
  { value: "nomeSkill", label: "Nome Skill" },
  { value: "idSkill", label: "Id Skill" },
  { value: "digitCode", label: "Digit Code" },
];
